### ISSUE TITLE
procd support for babel

### ISSUE THREAD

**Issue by kerneis** [openwrt-routing/packages#17]
Received on babel-users:

Over the past year openwrt has migrated over to an init replacement
called "procd"...

While the ideal situation is a daemon that never crashes, a better one
than presently is where babel is monitored and restarted properly. It
would be nice if babel could migrate over to USE_PROCD.

Regrettably the amount of rework required in babel.init is pretty
substantial, and it would be better if someone more intimate with
babel than I took it on.

a good example is in openwrt's repo for dropbear...

**Comment by zorun** [comment]
Closed via #250
