### ISSUE TITLE
babeld:  error is: Package babeld is missing dependencies for the following libraries

### ISSUE THREAD

**Issue by yanosz** [openwrt-routing/packages#211]
Trying to build babeld (branch: for-15.05, using SDK version 15.05.01) it failed:

`install -m0755 ./files/babeld.init /home/jan/src/routing_pages/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/babeld-1.7.1/ipkg-ar71xx/babeld/etc/init.d/babeld
find /home/jan/src/routing_pages/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/babeld-1.7.1/ipkg-ar71xx/babeld -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package babeld is missing dependencies for the following libraries:
libc.so.0
libgcc_s.so.1`
`Makefile:61: recipe for target '/home/jan/src/routing_pages/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/bin/ar71xx/packages/base/babeld_1.7.1-1_ar71xx.ipk' failed
make[3]: *** [/home/jan/src/routing_pages/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/bin/ar71xx/packages/base/babeld_1.7.1-1_ar71xx.ipk] Error 1
`

**Comment by kerneis** [comment]
@zorun any idea what is going on? I don't remember when I last tried to build 15.05.

**Comment by yanosz** [comment]
Hmm... this is strange. It doesn't seem to work, although I rember it to work yesterday :-/

**Comment by zorun** [comment]
I never used the SDK, I have no idea how it works.

I'll try building babeld from the latest OpenWRT 15.05 git.

**Comment by zorun** [comment]
`babeld` builds fine on the CC branch of OpenWRT (chaos_calmer@49403).
