### ISSUE TITLE
cjdns: update to cjdns-v19.1

### ISSUE THREAD

**Issue by l2dy** [openwrt-routing/packages#262]
@lgierth hyperboria's fork of cjdns is no longer active and they recommend pulling from https://github.com/cjdelisle/cjdns.git instead. Current release there is cjdns-v18 tagged on Oct 11, 2016.

**Comment by chpio** [comment]
it's v19.1 now

**Comment by lgierth** [comment]
I appreciate if someone could try and test the update -- otherwise I'll get to it soon-ish.

Happy about a certain level of interest in this package :)

**Comment by l2dy** [comment]
Fixed in dabd5842b4bd7c9506cb6b8f9f4df0fa2ca28523.

**Comment by chpio** [comment]
[the current version is 20.1](https://github.com/cjdelisle/cjdns/releases), isn't it?

**Comment by l2dy** [comment]
@chpio See 733e935f04fc6fa7a0e45fddca140cb9518995fe.

**Comment by chpio** [comment]
ohh... ok... that commit isn't new...
