### ISSUE TITLE
Batman-adv 2016.x for openwrt 12.09

### ISSUE THREAD

**Issue by sp2ong** [openwrt-routing/packages#287]
We have still use old router Ubiquiti Nanostation 2 which working very well with OpwenWRT v12.09

Is there a chance to appear possibility to use Batman-adv 2016.x ???:

https://github.com/openwrt-routing/packages/tree/for-12.09.x/batman-adv

Regards
Waldek

**Comment by mwarning** [comment]
@sp2ong batman-adv 2016.0 supports linux kernel up from 2.6.29. batman-adv 2016.1 needs at least linux kernel 3.2. See https://wirelesspt.net/wiki/Batman-adv_changelog
I do not know what linux kernel version OpwenWRT v12.09 uses.
