### ISSUE TITLE
nodogsplash.config wrong variable on "option idletimeout"

### ISSUE THREAD

**Issue by bvujnovac** [openwrt-routing/packages#292]
Hello, in .init file the variable name is "clientidletimeout"
but in .conf it is "idletimeout" so value assigned to that option defines nothing.
tested option "clientidletimeout" set to some value and it works.

**Comment by mwarning** [comment]
@bvujnovac thanks for reporting. Should be fixed very soon.

**Comment by mwarning** [comment]
@porjo the change didn't make it into 17.01.1/2, but should be included in the next major release.
