### ISSUE TITLE
Install bmx6*, bmx7-tun, and bmx7-table on LEDE 17.01.2 fails

### ISSUE THREAD

**Issue by Admin-DataRoads** [openwrt-routing/packages#323]
` Installing bmx6 (r2017021601-4) to root...`
` Downloading http://downloads.lede-project.org/releases/17.01.2/packages/arm_cortex- a9_vfpv3/routing/bmx6_r2017021601-4_arm_cortex-a9_vfpv3.ipk`
` Collected errors:`
`  * satisfy_dependencies_for: Cannot satisfy the following dependencies for bmx6:`
`  * 	kernel (= 4.4.71-1-9f18c9c8eae6a4bfe17f419b398e25cd) * 	kernel (= 4.4.71-1-9f18c9c8eae6a4bfe17f419b398e25cd) * `
`  * opkg_install_cmd: Cannot install package bmx6.`

Repeat for every bmx6* package...

`Installing bmx7-tun (r2017071001-4) to root...`
`Downloading http://downloads.lede-project.org/releases/17.01.2/packages/arm_cortex-a9_vfpv3/routing/bmx7-tun_r2017071001-4_arm_cortex-a9_vfpv3.ipk`
`Collected errors:`
` * satisfy_dependencies_for: Cannot satisfy the following dependencies for bmx7-tun:`
` * 	kernel (= 4.4.71-1-9f18c9c8eae6a4bfe17f419b398e25cd) * 	kernel (= 4.4.71-1-9f18c9c8eae6a4bfe17f419b398e25cd) * `
` * opkg_install_cmd: Cannot install package bmx7-tun.`
...

` * satisfy_dependencies_for: Cannot satisfy the following dependencies for bmx7-table:`
` * 	kernel (= 4.4.71-1-9f18c9c8eae6a4bfe17f419b398e25cd) * 	kernel (= 4.4.71-1-9f18c9c8eae6a4bfe17f419b398e25cd) * `
` * opkg_install_cmd: Cannot install package bmx7-table.`

All other bmx7* packages installed without issue.

More specifically this is on ROOter GoldenOrb 2017-07-01 on a Linksys WRT3200ACM. Please let me know if the problem is specific to this release. LibreMesh.org (domain is down) doesn't seem to support the WRT3200ACM yet, and I need 3G/4G modem and tether support with MWAN failover and load balancing.

**Comment by p4u** [comment]
It seems that the kernel you are using in your device is not the same of the one used to build the packages.

**Comment by Admin-DataRoads** [comment]
These install attempts used the opkg published installs for the LEDE 17.01.2 release, so the problem is probably somewhere between the buildbots and opkg repositories. I'll go ahead and close this out for now while I re-test bmx installs using opkg on the newest (.4) release.
