### ISSUE TITLE
new olsrd config structure makes Freifunk node updates nearly impossible

### ISSUE THREAD

**Issue by thuehn** [openwrt-routing/packages#36]
Hi all,

The olsrd config structure changes prevent a proper migration in a productiv Freifunk network. We have about 100 nodes, all using /etc/config/olsrd as config file. With the new /etc/config/olsrd4 config strucutre, the routing deamon will not start, so the mesh routing is down. A manual move of /etc/config/olsrd into /etc/config/olsrd4 and aditionally removing the IpVersion option is needed to get the current olsrd code running on a productive Freifunk mesh. From my point of view this makes is impossible to migrate to the new olsrd config structure.
I could imageing that /etc/config/olsrd stays and just /etc/config/olsrd6 is added. And the IpVersion check just gives a warning and does not prevend olsrd deamon to start.

Greetings from Berlin

**Comment by bittorf** [comment]
can this issue be closed?
