### ISSUE TITLE
Add @wfleurant to repo collaborators

### ISSUE THREAD

**Issue by lgierth** [openwrt-routing/packages#398]
Hey friends,

I've not been the most active maintainer of the cjdns packages in a long while. @wfleurant, who was the original author of that bunch of code, is generally a human being extraordinaire and still actively working with cjdns and has offered to take over maintainership of `cjdns` and `luci-app-cjdns`.

Just wanted to get a quick sanity check here before I add him as a collaborator to the repo.

Cool? Thanks!

**Comment by mwarning** [comment]
@lgierth as for me, I think it is great to have more people on board. +1

**Comment by lgierth** [comment]
Thanks for the positive feedback -- adding @wfleurant now!

(I should have timeboxed this, but 1 week seems plenty for a *quick sanity check*.)

**Comment by lgierth** [comment]
@wfleurant yoiu have an invitation, make yourself at home. Best first thing to do is update the maintainer line in the packages :)

**Comment by mwarning** [comment]
Don't forget to always make a pull request and try to let someone else to review/merge it (there might be exceptions..). :-)
