### ISSUE TITLE
[batadv] continuous log messages from netifd

### ISSUE THREAD

**Issue by yogo1212** [openwrt-routing/packages#428]
every now and then, syslog is filled with these messages on boot:

```
Thu Nov 15 11:48:33 2018 daemon.notice netifd: Interface 'mesh' is setting up now
Thu Nov 15 11:48:34 2018 daemon.notice netifd: mesh (17773): ./batadv.sh: eval: line 22: can't create /sys/class/net//batman_adv/mesh_iface: nonexistent directory
Thu Nov 15 11:48:34 2018 daemon.notice netifd: mesh (17773): Command failed: Invalid argument
Thu Nov 15 11:48:34 2018 daemon.notice netifd: mesh (17780): ./batadv.sh: eval: line 31: can't create /sys/class/net//batman_adv/mesh_iface: nonexistent directory
Thu Nov 15 11:48:34 2018 daemon.notice netifd: Interface 'mesh' is now down
Thu Nov 15 11:48:34 2018 daemon.notice netifd: Interface 'mesh' is setting up now
... # repeat
```

the messages stop after running `/etc/init.d/network restart`.
`reload` isn't enough. `wifi` also has no effect.

looking at https://github.com/openwrt-routing/packages/blob/master/batman-adv/files/lib/netifd/proto/batadv.sh, it appears the `iface` var is empty.
```
echo "$mesh" > "/sys/class/net/$iface/batman_adv/mesh_iface"
```

**Comment by yogo1212** [comment]
`{"proto":"batadv","mesh":"bat0","type":"mesh","mtu":1540}`

**Comment by ecsv** [comment]
Looks at first glance like a netifd problem. Since both netifd and the batman-adv configuration changed, can you please check whether it still happens with OpenWrt master?

**Comment by yogo1212** [comment]
@ecsv i was thinking the same thing.
the script detecting this error also creates a file indicating that it became active.
~20 test routers have been running the updated version since thursday and none of them have run into this issue.
next week, i'll deploy the new firmware to prod.

looking good so far :+1:

**Comment by yogo1212** [comment]
have not seen this again - let's assume the integration fixed it.
