### ISSUE TITLE
bmx7-info calls returns an invalid JSON structure when no interfaces are configured or no links are established

### ISSUE THREAD

**Issue by rogerpueyo** [openwrt-routing/packages#430]
Certain bmx7-info calls from the web interface (e.g., https://192.168.1.1/cgi-bin/bmx7-info?$info) return an invalid JSON structure with two consecutive commas. This happens when there are no interfaces configured to be used, or when no links can be established to other routers.

Take, for instance, this example, with **two commas** just before the _memory_ block:

```json
	"info": [{
		"status": {
			"shortId": "EE598CB5",
			etc.
		}
	}, {
		"interfaces": [{
			"dev": "br-lan",
			"state": "UP",
			etc.
		}, {
			"dev": "eth1",
			"state": "UP",
			etc.
		}]
	}, , {
		"memory": {
			"bmx7": "2388 kB"
		}
	}]
}
```

**Comment by p4u** [comment]
Good catch, this happens if there are no links. Please send PR.
