### ISSUE TITLE
babeld: Add stable patches

### ISSUE THREAD

**Issue by adrianschmutzler** [openwrt-routing/packages#481]
The last babeld update has been in Nov 2018, and I would like to have the two patches from the 1.8 stable branch included here (https://github.com/jech/babeld/commits/babeld-1.8-branch).

Can I just add them in a PR or is there anything speaking against it (since we have no local babeld patches so far)?
I already do it that way in my own repo ...

**Comment by kerneis** [comment]
> Can I just add them in a PR or is there anything speaking against it (since we have no local babeld patches so far)?
>  I already do it that way in my own repo ...

We've had patches in the past I think, we just don't have any that make sense right now but feel free to add a pull request.

Gabriel

**Comment by adrianschmutzler** [comment]
https://github.com/openwrt-routing/packages/pull/482
