### ISSUE TITLE
batman-adv: deletes /etc/config/batman-adv

### ISSUE THREAD

**Issue by mwarning** [openwrt-routing/packages#499]
Steps to replicate:
1. compile OpenWrt master with `files/etc/config/batman-adv`in the openwrt build root:
```
config mesh 'bat0'
	option gw_mode 'client'
```
2. flash sysupgrade image
3. `/etc/config/batmna-adv` does not exist. But `/rom/etc/config/batman-adv`does.

**Comment by mwarning** [comment]
@ecsv ping

Also happens with the  openwrt-19.07 branch.

**Comment by ecsv** [comment]
Hu? This is planned and part of the migration script from 54af5a209e0a0a75b5eb712c0ca8056e66de02c0

**Comment by mwarning** [comment]
Uhm, I've never heard about this. But it looks good.
