### ISSUE TITLE
opennds - not available in openwrt repositories

### ISSUE THREAD

**Issue by sicelo** [openwrt-routing/packages#572]
I am not sure if this is the correct place to report this, but opennds does not seem to be built for the official openwrt repository at https://downloads.openwrt.org/releases/packages-19.07/

Please let me know if there's an alternative repo for it.

**Comment by SvenRoederer** [comment]
opennds is only in the master branch of the repo. So it's not avail on openwrt-19.07 anyway.

**Comment by sicelo** [comment]
Indeed. Is there a reason for this? Or, anything we can do to get it in the openwrt branch?

**Comment by SvenRoederer** [comment]
You can backport the software to 19.07 branch.
It will very likely work. Probably just cherry-picking them from master will be enough.
