### ISSUE TITLE
Adopt circleci from packages feed?

### ISSUE THREAD

**Issue by PolynomialDivision** [openwrt-routing/packages#577]
Why not using the same https://github.com/openwrt/packages/tree/master/.circleci?

**Comment by SvenRoederer** [comment]
That's very similar to what @lynxis suggested in https://github.com/openwrt-routing/packages/pull/215. @yanosz PR #215 seems stalled anyway.

**Comment by lynxis** [comment]
go for it!

**Comment by mwarning** [comment]
@PolynomialDivision can you make a pull request?

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision can you make a pull request?

but someone has to acrivate that on circleci package

**Comment by mwarning** [comment]
@PolynomialDivision we can setup this together on Wednesday if you like. I do not have much experience with setting this things up.  @lynxis do you want to join?

**Comment by PolynomialDivision** [comment]
Or we just move this feed to packages feed as subdirectory?

**Comment by SvenRoederer** [comment]
> Or we just move this feed to packages feed as subdirectory?

As discussed in #184 ?

**Comment by PolynomialDivision** [comment]
Yes. ^^

**Comment by PolynomialDivision** [comment]
https://github.com/openwrt-routing/packages/pull/661

**Comment by PolynomialDivision** [comment]
Done.
